### ISSUE TITLE
Lowering Threshold Error when going through large file

### ISSUE THREAD

**Issue by vjoshi48** [UEFepilepsyAIVI/DeepSqueak#4] opened 2021-12-14 20:08 UTC
![deepsqueak](https://user-images.githubusercontent.com/77455331/146071784-39b6e8e3-f143-49d6-8e4e-58b45966151f.PNG)
I am trying to load a rather large USV file when doing unsupervised clustering, and when I do, a strange error happens. The file will load until a certain point and then it will get stuck while I get a message in Matlab saying "lowering threshold" repeatedly. I have had this happen before in DeepSqueak when I am labelling calls. If I make the bounding box on a call too small, the program would similarly freeze and continuously display the message "lowering threshold". I suspect that the file stops loading because it reaches a USV that has a bounding box that is too small. I am new to asking questions on Github, so let me know what other information would be helpful in diagnosing this error. Thank you.

**Comment by leonardolv** [comment] 2021-12-15 18:39
Hi,
We recently merged the Screener version with the original DeepSqueak, it is more stable and faster.
You can download it here:
https://github.com/DrCoffey/DeepSqueak

Let us know if the problem is solved in the new version.

Best,

Leonardo

**Comment by vjoshi48** [comment] 2021-12-21 19:36
Thank you so much! This did fix the issue.

-Varun Joshi

Varun Joshi | He/Him
Presidential Scholar | GSU Honors College 2024
Data Science Major

________________________________

**Closed as completed** 2022-03-02 17:50 UTC
